# @package model

# settings
use_flip: false
num_worker: 1
n_train: 1000
train_coarse: 0
useSeg: false
#useSeg: true

lmk_weight: 1
useWlmk: true
shape_reg: 0.0001
exp_reg: 0.0001
tex_reg: 0.0001
light_reg: 12
photow: 2
idw: 0.12
useConstraint: true
mrfwr: 0.01
zregw: 0.005
zdiffw: 0.005
zsymw: 0.005
consr: 1
sfsw:
- 5
- 0
- 0
- 0

resume_training: False

# training related (to remove)
e_lr: 0.0001
multi_gpu: false
n_epoch: 500

# data related
training_data: vox1  #to remove